### ISSUE TITLE
hi.  error

### ISSUE THREAD

**Issue by unclemake** [sparkbitpl/immutable-ts#1]
import { Immutable, ImmutableUtils } from "immutable-typescript";

let immutable = ImmutableUtils.asImmutable({ a: 1 });
let newImmutable = ImmutableUtils.update(immutable).set('a', 1);

// Here it should be true
console.log('test', immutable === newImmutable);  // test,false

**Comment by jedrekfulara** [comment]
@unclemake - this is the expected behaviour. You are creating a new object: the set operation always results in a new instance, even if you set the same value.

**Comment by unclemake** [comment]
immutable set the same value. Does not generate new object.
I think this is a bug.
used in redux。Will lead to unnecessary performance consumption。

**Comment by jedrekfulara** [comment]
We will add this kind of optimization (if the new value is === the old value, just return the same object) in a future release.
